/**
 * Digital modulation/demodulation: ASK, FSK, PSK, QAM, PCM
 *
 * All digital demodulators accept numBits as a parameter so they stay in sync
 * with the actual bit stream length generated by useRadio (which varies with bitRate).
 */

// 16-QAM Gray-coded alphabet on each axis: {-3,-1,+1,+3}/sqrt(10)
const QAM_ALPHABET = [-3, -1, 1, 3].map(v => v / Math.sqrt(10));
const QAM_GRAY_MAP = [0, 1, 3, 2]; // 2-bit Gray code: index→Gray value

// --- ASK ---

export function modulateASK(n: number, omega: number, bitStream: Uint8Array): Float32Array {
    const out = new Float32Array(n);
    const spb = Math.floor(n / bitStream.length);
    for (let b = 0; b < bitStream.length; b++) {
        const amp = bitStream[b] ? 1 : 0;
        for (let s = 0; s < spb; s++) {
            const idx = b * spb + s;
            if (idx < n) out[idx] = amp * Math.sin(omega * idx);
        }
    }
    return out;
}

/**
 * ASK envelope detector: rectify → LPF → per-symbol threshold.
 * Outputs ±1 stepped waveform.
 */
export function demodulateASK(signal: Float32Array, sr: number, carrierFreq: number, numBits = 16): Float32Array {
    const n = signal.length;
    const spb = Math.floor(n / numBits);

    // Compute per-sample envelope with causal LPF (half-win = 1 carrier period)
    const halfWin = Math.max(2, Math.floor(sr / carrierFreq));
    const prefix = new Float32Array(n + 1);
    for (let i = 0; i < n; i++) prefix[i + 1] = prefix[i] + Math.abs(signal[i]);
    const envelope = new Float32Array(n);
    for (let i = 0; i < n; i++) {
        const lo = Math.max(0, i - halfWin);
        const hi = Math.min(n - 1, i + halfWin);
        envelope[i] = (prefix[hi + 1] - prefix[lo]) / (hi - lo + 1);
    }

    // Global max for adaptive threshold
    let maxEnv = 0;
    for (let i = 0; i < n; i++) maxEnv = Math.max(maxEnv, envelope[i]);
    const threshold = maxEnv * 0.5;

    const out = new Float32Array(n);
    for (let b = 0; b < numBits; b++) {
        const start = b * spb;
        const end = Math.min(n, start + spb);
        let sumEnv = 0;
        for (let i = start; i < end; i++) sumEnv += envelope[i];
        const val = (sumEnv / (end - start)) > threshold ? 1 : -1;
        for (let i = start; i < end; i++) out[i] = val;
    }
    return out;
}

// --- FSK ---

export function modulateFSK(n: number, sr: number, carrierFreq: number, bitStream: Uint8Array): Float32Array {
    const out = new Float32Array(n);
    const spb = Math.floor(n / bitStream.length);
    const fHigh = carrierFreq + 500;
    const fLow  = carrierFreq - 500;
    for (let b = 0; b < bitStream.length; b++) {
        const w = 2 * Math.PI * (bitStream[b] ? fHigh : fLow) / sr;
        for (let s = 0; s < spb; s++) {
            const idx = b * spb + s;
            if (idx < n) out[idx] = Math.sin(w * idx);
        }
    }
    return out;
}

/**
 * FSK dual-frequency correlator: compares energy at fHigh vs fLow per symbol.
 * Outputs ±1 stepped waveform.
 */
export function demodulateFSK(signal: Float32Array, sr: number, carrierFreq: number, numBits = 16): Float32Array {
    const n = signal.length;
    const spb = Math.floor(n / numBits);
    const wH = 2 * Math.PI * (carrierFreq + 500) / sr;
    const wL = 2 * Math.PI * (carrierFreq - 500) / sr;
    const out = new Float32Array(n);

    for (let b = 0; b < numBits; b++) {
        const start = b * spb;
        const end = Math.min(n, start + spb);
        let IH = 0, QH = 0, IL = 0, QL = 0;
        for (let i = start; i < end; i++) {
            IH += signal[i] * Math.cos(wH * i);
            QH += signal[i] * -Math.sin(wH * i);
            IL += signal[i] * Math.cos(wL * i);
            QL += signal[i] * -Math.sin(wL * i);
        }
        const val = (IH * IH + QH * QH) > (IL * IL + QL * QL) ? 1 : -1;
        for (let i = start; i < end; i++) out[i] = val;
    }
    return out;
}

// --- PSK (BPSK) ---

export function modulatePSK(n: number, omega: number, bitStream: Uint8Array): Float32Array {
    const out = new Float32Array(n);
    const spb = Math.floor(n / bitStream.length);
    for (let b = 0; b < bitStream.length; b++) {
        const phase = bitStream[b] ? 0 : Math.PI; // bit 1 → 0°, bit 0 → 180°
        for (let s = 0; s < spb; s++) {
            const idx = b * spb + s;
            if (idx < n) out[idx] = Math.sin(omega * idx + phase);
        }
    }
    return out;
}

/**
 * PSK coherent correlator: correlates each symbol with reference sin(ωt).
 * Positive correlation → bit 1 (+1), negative → bit 0 (−1).
 */
export function demodulatePSK(signal: Float32Array, sr: number, carrierFreq: number, numBits = 16): Float32Array {
    const n = signal.length;
    const spb = Math.floor(n / numBits);
    const omega = 2 * Math.PI * carrierFreq / sr;
    const out = new Float32Array(n);

    for (let b = 0; b < numBits; b++) {
        const start = b * spb;
        const end = Math.min(n, start + spb);
        let corr = 0;
        for (let i = start; i < end; i++) corr += signal[i] * Math.sin(omega * i);
        const val = corr > 0 ? 1 : -1;
        for (let i = start; i < end; i++) out[i] = val;
    }
    return out;
}

// --- QAM (16-QAM) ---

export function modulateQAM(n: number, omega: number, bitStream: Uint8Array): Float32Array {
    const out = new Float32Array(n);
    const numSymbols = Math.floor(bitStream.length / 4); // 4 bits per symbol
    const spb = Math.floor(n / numSymbols);

    for (let sym = 0; sym < numSymbols; sym++) {
        const b = bitStream.slice(sym * 4, sym * 4 + 4);
        const I_bits = (b[0] << 1) | b[1];
        const Q_bits = (b[2] << 1) | b[3];
        const I = QAM_ALPHABET[QAM_GRAY_MAP.indexOf(I_bits)];
        const Q = QAM_ALPHABET[QAM_GRAY_MAP.indexOf(Q_bits)];
        for (let s = 0; s < spb; s++) {
            const idx = sym * spb + s;
            if (idx < n) out[idx] = I * Math.cos(omega * idx) - Q * Math.sin(omega * idx);
        }
    }
    return out;
}

/**
 * 16-QAM coherent demodulator.
 * numBits: actual bit count from the modulated stream (must match modulator).
 * numSymbols = numBits / 4.
 *
 * Waveform output: decoded bits at the ORIGINAL BIT RATE (numBits steps),
 * so it aligns with the message waveform for visual comparison.
 */
export function demodulateQAM(
    signal: Float32Array,
    sr: number,
    carrierFreq: number,
    numBits = 16
): { waveform: Float32Array; constellation: { I: number; Q: number }[] } {
    const n = signal.length;
    const omega = 2 * Math.PI * carrierFreq / sr;
    const numSymbols = Math.max(1, Math.floor(numBits / 4));
    const spb = Math.floor(n / numSymbols);
    const spb_bit = Math.floor(n / numBits);
    const out = new Float32Array(n);
    const constellation: { I: number; Q: number }[] = [];

    /** Find nearest alphabet index for a given soft value. */
    const nearestIdx = (val: number): number => {
        let best = 0, minD = Infinity;
        for (let k = 0; k < QAM_ALPHABET.length; k++) {
            const d = Math.abs(val - QAM_ALPHABET[k]);
            if (d < minD) { minD = d; best = k; }
        }
        return best;
    };

    for (let sym = 0; sym < numSymbols; sym++) {
        const start = sym * spb;
        const end = Math.min(n, start + spb);

        let I = 0, Q = 0;
        for (let i = start; i < end; i++) {
            I += signal[i] * Math.cos(omega * i);
            Q += signal[i] * -Math.sin(omega * i);
        }
        const cnt = end - start || 1;
        I = (2 * I) / cnt;
        Q = (2 * Q) / cnt;
        constellation.push({ I, Q });

        const bestI_idx = nearestIdx(I);
        const bestQ_idx = nearestIdx(Q);

        const gI = QAM_GRAY_MAP[bestI_idx];
        const gQ = QAM_GRAY_MAP[bestQ_idx];
        const bits = [
            (gI >> 1) & 1, gI & 1,
            (gQ >> 1) & 1, gQ & 1
        ];

        for (let b = 0; b < 4; b++) {
            const val = bits[b] ? 1 : -1;
            const bitStart = (sym * 4 + b) * spb_bit;
            const bitEnd = Math.min(n, bitStart + spb_bit);
            for (let i = bitStart; i < bitEnd; i++) out[i] = val;
        }
    }

    return { waveform: out, constellation };
}

// --- PCM ---

export function modulatePCM(n: number, sr: number, message: Float32Array): Float32Array {
    const out = new Float32Array(n);
    const bps = 4; // bits per sample
    // 0.5ms per bit → bitTotal=88 → word rate ≈ 501 Hz (5 words/cycle at 100Hz message).
    // 2ms/bit (old) gave word rate 125 Hz — sub-Nyquist for 100Hz → missed square-wave half-cycles.
    const spb = Math.floor(sr * 0.0005);

    // Normalize message to [-1, 1] so the full 4-bit quantizer range is utilized.
    // Without normalization (message amplitude 0.5), only 8 of 16 levels are used
    // causing severe quantization bias in the decoded output.
    let maxMsg = 0;
    for (let i = 0; i < message.length; i++) maxMsg = Math.max(maxMsg, Math.abs(message[i]));
    const scale = maxMsg > 1e-10 ? 1 / maxMsg : 1;

    for (let i = 0; i < n; i += spb * bps) {
        const msgNorm = message[Math.min(n - 1, i)] * scale; // normalized to [-1, 1]
        // Use round (not floor) to minimize quantization bias
        const val = Math.min(15, Math.max(0, Math.round((msgNorm + 1) / 2 * 15)));
        for (let b = 0; b < bps; b++) {
            const bit = (val >> (3 - b)) & 1;
            for (let s = 0; s < spb && (i + b * spb + s) < n; s++) {
                out[i + b * spb + s] = bit ? 1 : -1;
            }
        }
    }
    return out;
}

/**
 * PCM decoder: integrate 4-bit words and reconstruct stepped sample values.
 * Facade DC removal + normalize handles amplitude alignment with message display.
 */
export function demodulatePCM(signal: Float32Array, sr: number): Float32Array {
    const n = signal.length;
    const out = new Float32Array(n);
    const bps = 4;
    const spb = Math.floor(sr * 0.0005); // must match modulatePCM
    const bitTotal = spb * bps;

    for (let i = 0; i < n; i += bitTotal) {
        let val = 0;
        for (let b = 0; b < bps; b++) {
            let sum = 0;
            for (let s = 0; s < spb && (i + b * spb + s) < n; s++) {
                sum += signal[i + b * spb + s];
            }
            if (sum > 0) val |= (1 << (bps - 1 - b));
        }
        const sampleVal = (val / 15) * 2 - 1;
        for (let s = 0; s < bitTotal && (i + s) < n; s++) out[i + s] = sampleVal;
    }
    return out;
}
